spring:
  config:
    import: optional:application-secret.yml
    
  application:
    name: buybook

  datasource:
    url: jdbc:postgresql://localhost:5432/buybook
    driver-class-name: org.postgresql.Driver
    
    # 커넥션 풀 설정
    hikari:
      maximum-pool-size: 10  # 커넥션 풀 크기
      minimum-idle: 5        # 최소 아이들 커넥션 수
      idle-timeout: 30000    # 커넥션 풀에서의 커넥션 최대 유휴 시간 (밀리초)
      max-lifetime: 600000   # 커넥션 풀에서의 커넥션 최대 수명 (밀리초)
      connection-timeout: 30000  # 커넥션 요청에 대한 타임아웃 (밀리초)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect